# Generated by Django 4.2.4 on 2023-08-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_apilog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apilog",
            options={"verbose_name": "API Log", "verbose_name_plural": "API Logs"},
        ),
        migrations.AddField(
            model_name="apilog",
            name="request_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apilog",
            name="response_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
