# Generated by Django 4.2.4 on 2023-10-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_apilog_options_apilog_request_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestersEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("requested_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
